# Idempotent Provisioning, must be changed for a new instance
provision_token: 1eb03971e25f4211b54b58c77198688f

# RHEL 7 Image Id
# See https://github.kdc.capitalone.com/public-cloud/AMI/blob/master/rhel7.json
image: ami-3b45b250

# Instance type
instance_type: m3.medium

# SSH Key from AWS
key: KapilStsDigitalDevEast

# AWS Region
region: us-east-1

# Security Groups, minimum should include ssh connectivity from COF
security_groups:
 - sg-30bc2c55

# Subnet group to uilize for instance
subnet: subnet-6d28382b

# Default Tags
tags:
  CMDBEnvironment: ENVPPDIGITALSUPPORTSERVICES
  ASV: ASVDIGITALSUPPORTSERVICES
  OwnerContact: ylv522
  Owner: ylv522
  Role: CloudMaid
  Version: 0.1