
- hosts: all
  tasks:
   - name: Install Base Packages
     yum: name={{ item }} state=present
     become: true
     with_items:
       - git
       - python-virtualenv
       - bzip2
       - psmisc
    
   - name: Install Dev Packages
     yum: name={{ item }} state=present
     become: true
     with_items:
       - nano
       - tmux

   - name: Create maid group
     become: true
     group: >
       name=maid
       state=present

   - name: Create maid user
     become: true     
     user: >
       name=maid
       group=maid

   - name: Create maid directories
     become: true     
     file: >
       state=directory
       path={{ item }}
       owner=maid
       group=maid
       mode=0755
     with_items:
       - /etc/maid
       - /etc/maid/policies
       - /var/log/maid
       - /var/cache/maid
       - /usr/local/maid

   - name: Fetch maid source
     become: true
     git: repo="https://github.kdc.capitalone.com/ylv522/cloud-janitor.git" dest="/usr/local/maid"    

   - name: Install PyPy
     become: true
     unarchive: src="deps/pypy-2.6.1-linux_x86_64-portable.tar.bz2" dest="/usr/local"

   - name: Link pypy
     become: true
     file: state="link" src="/usr/local/pypy-2.6.1-linux_x86_64-portable" dest="/usr/local/pypy"     

   - name: Install Deps
     pip: state=present requirements=/usr/local/maid/requirements.txt virtualenv_python=/usr/local/pypy/bin/pypy
     environment:
       http_proxy: {{ http_proxy }}
       https_proxy: {{ https_proxy }}
