
- name: Install Base Packages
  yum: name={{ item }} state=present
  with_items:
    - git
    - python-virtualenv

- name: Install Dev Packages
  yum: name={{ item }} state=present
  with_items:
    - nano
    - tmux
    - emacs-nox    

- name: Create maid group
  group: >
    name=maid
    state=present

- name: Create maid user
  user: >
    name=maid
    group=maid

- name: Create maid directories
  file: >
    state=directory
    path={{ item }}
    owner=maid
    group=maid
    mode=0755
  with_items:
    - /etc/maid
    - /etc/maid/policies
    - /var/log/maid
    - /var/cache/maid
    - /usr/local/maid

- name: Fetch maid source
  git:
    repo: "https://github.kdc.capitalone.com/ylv522/cloud-janitor.git"
    dest: "/usr/local/maid/maid"    
